#ifndef CONSTANTS_H
#def CONSTANTS_H

// GENERAL
#define ALL_BITS (0xFF >> 2)

// PINS
#define R_BUTTON_B GPIO_PIN_0
#define L_BUTTON_B GPIO_PIN_1
#define REVERSE_BUTTON_F GPIO_PIN_0
#define PERIPHERAL_BUTTON_F GPIO_PIN_1
#define SOUND_PIN_E GPIO_PIN_0
#define NUMBER_OF_ANALOG_PINS 1

#endif //CONSTANTS_H//