#ifndef CONSTANTS_H
#define CONSTANTS_H

// GENERAL
#define FORWARD 0
#define REVERSE 1
#define DOG_3_THRESHOLD 1100
#define DOG_2_THRESHOLD 1400
#define DOG_1 1
#define DOG_2 2
#define DOG_3 3

// TIMING
#define TicksPerMS 40000
#define PWMTicksPerMS TicksPerMS/32
#define MotorFreqHz 2000
#define ServoFreqHz 50
#define MOTOR_PWM_PERIOD PWMTicksPerMS*1000/MotorFreqHz
#define SERVO_PWM_PERIOD PWMTicksPerMS*1000/ServoFreqHz
#define LEFT_SERVO_IDLE_DUTY (SERVO_PWM_PERIOD >> 2)*(5/100)
#define RIGHT_SERVO_IDLE_DUTY (SERVO_PWM_PERIOD >> 2)*(5/100)
#define I2C_COMM_SPEED 9

// PINS
#define THRUST_FAN_DIR_B GPIO_PIN_0
#define DOG_TAG_E GPIO_PIN_0
#define NUMBER_OF_ANALOG_PINS 1
#define LEFT_SERVO_PIN_B GPIO_PIN_4
#define LEFT_SERVO_BIT 4
#define RIGHT_SERVO_PIN_B GPIO_PIN_5
#define RIGHT_SERVO_BIT 5
#define THRUST_FAN_PWM_PIN_B GPIO_PIN_6
#define THRUST_FAN_PWM_BIT 6
#define INDICATOR_PIN_B GPIO_PIN_7
#define INDICATOR_BIT 7
#define I2C_SDA_PIN GPIO_PIN_3
#define I2C_SCL_PIN GPIO_PIN_2
#define I2C_SDA_BIT 3
#define I2C_SCL_BIT 2

// PERIPHERAL/REGISTER
#define ALL_BITS (0xFF << 2)
#define PWM_PIN_M 0x0000ffff
#define I2C_PIN_M 0xffff00ff
#define GenA_0_Normal (PWM_0_GENA_ACTCMPAU_ONE | PWM_0_GENA_ACTCMPAD_ZERO)
#define GenB_0_Normal (PWM_0_GENB_ACTCMPBU_ONE | PWM_0_GENB_ACTCMPBD_ZERO)
#define GenA_1_Normal (PWM_1_GENA_ACTCMPAU_ONE | PWM_1_GENA_ACTCMPAD_ZERO)
#define GenB_1_Normal (PWM_1_GENB_ACTCMPBU_ONE | PWM_1_GENB_ACTCMPBD_ZERO)
#define GenA_0_Invert (PWM_0_GENA_ACTCMPAU_ZERO | PWM_0_GENA_ACTCMPAD_ONE)
#define GenB_0_Invert (PWM_0_GENB_ACTCMPBU_ZERO | PWM_0_GENB_ACTCMPBD_ONE)
#define BitsPerNibble 4

#endif //CONSTANTS_H//
